"""add model_configs

Revision ID: 04569358397f
Revises: bb519d176084
Create Date: 2026-07-02 15:43:20.127434
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Alembic 版本标识。
revision: str = '04569358397f'
down_revision: str | None = 'bb519d176084'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('purpose', sa.Enum('text', 'image', 'video'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_ciphertext', sa.VARBINARY(length=512), nullable=False),
    sa.Column('dek_ciphertext', sa.VARBINARY(length=512), nullable=False),
    sa.Column('api_key_masked', sa.String(length=32), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.Column('provider_options', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invalid'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_tested_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('active_key', sa.String(length=128), sa.Computed("CASE WHEN is_active=1 THEN CONCAT(user_id,'-',purpose) ELSE NULL END", persisted=False), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_model_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configs')),
    sa.UniqueConstraint('active_key', name=op.f('uq_model_configs_active_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_index(op.f('ix_model_configs_user_id'), 'model_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL:drop_table 会级联删除表上的索引与外键,故无需(且不可)在删表前单独
    # drop_index —— 被 FK 占用的索引单独 drop 会触发 MySQL 1553。直接删表即可。
    op.drop_table('model_configs')
    # ### end Alembic commands ###
